[package]
authors = ["madiele92@gmail.com"]
edition = "2021"
name = "VoDToPodcastRSS"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
actix-rt = "1.1"
actix-web = "3.1"
anyhow = "1.0.33"
config = "0.13.1"
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.4"
reqwest = "0.11"
serde = "1.0"
serde_json = "1.0.59"
thiserror = "1.0"
tokio = "1.22"
uuid = "1.2"
