[package]
authors = ["madiele92@gmail.com"]
edition = "2021"
name = "vod2pod-rss"
version = "1.0.4"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
actix-rt = "=2.9.0"
actix-web = "=4.3.1"
async-trait = "=0.1.73"
url = { version="*", features = ["serde"]}
futures = "=0.3.28"
log = "=0.4.20"
regex = "=1.9.4"
reqwest = { version = "=0.11.20", features = ["json"] }
serde = "=1.0.188"
serde_json = "=1.0.105"
tokio = { version = "=1.32.0" , features = ["macros", "process"]}
uuid = { version= "=1.4.1", features = ["v4", "serde"]}
genawaiter = {version = "=0.99", features = ["futures03"] }
rss = { version = "=2.0", features = ["serde"] }
eyre = "=0.6"
simple_logger = "=4.2"
redis = { version = "=0.23", features = ["tokio-comp"] }
feed-rs = "=1.3.0"
md5 = "=0.7.0"
mime = "=0.3.17"
cached = { version = "=0.44.0", features = ["redis_tokio"] }
iso8601-duration = "=0.2.0"
chrono = "=0.4.26"

[dev-dependencies]
temp-env ={ version = "=0.3.4", features = ["async_closure"] }
env_logger = "*"
test-log = "0.2.11"
