[package]
authors = ["madiele92@gmail.com"]
edition = "2021"
name = "vod_to_podcast_rss"
version = "0.1.0"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.2.1"
actix = "0.13"
actix-redis = "0.12"
async-trait = "0.1.58"
url = { version="*", features = ["serde"]}
anyhow = "1.0.66"
config = "0.13.2"
futures = "0.3.25"
log = "0.4.17"
pretty_env_logger = "0.4.0"
regex = "1.7.0"
reqwest = "0.11.12"
serde = "1.0.147"
serde_json = "1.0.87"
serde-resp = "0.3"
thiserror = "1.0.37"
tokio = { version = "1.21.2" , features = ["macros", "process"]}
tokio-test = "0.4.2"
uuid = { version= "1.2.1", features = ["v4", "serde"]}
ffmpeg-next = "5.1"
genawaiter = {version = "0.99", features = ["futures03"] }
rss = { version = "2.0", features = ["serde"] }
eyre = "0.6"
simple_logger = "4.0"
redis = { version = "0.22", features = ["tokio-comp"] }
feed-rs = "1.3.0"
md5 = "0.7.0"

[dev-dependencies]
mockall = "0.11.3"
