[package]
authors = ["madiele92@gmail.com"]
edition = "2021"
name = "vod2pod-rss"
version = "1.2.3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
actix-rt = "=2.10.0"
google-youtube3 = "=5.0.4"
actix-web = "=4.9.0"
async-trait = "=0.1.81"
url = { version="=2.5.2", features = ["serde"]}
futures = "=0.3.30"
log = "=0.4.22"
regex = "=1.10.6"
reqwest = { version = "=0.12.5", features = ["json"] }
serde = "=1.0.206"
serde_json = "=1.0.124"
tokio = { version = "=1.39.2", features = ["macros", "process"]}
uuid = { version= "=1.10.0", features = ["v4", "serde"]}
genawaiter = {version = "=0.99", features = ["futures03"] }
openssl = { version = "*", features = ["vendored"] } #this is here just to make cross-compiling work during github actions
rss = { version = "=2.0", features = ["serde"] }
eyre = "=0.6"
simple_logger = "=5.0"
redis = { version = "=0.26", features = ["tokio-comp"] }
mime = "=0.3.17"
cached = { version = "=0.53.1", features = ["redis_tokio"] }
iso8601-duration = "=0.2.0"
chrono = "=0.4.38"
feed-rs = "=2.1.0"

[dev-dependencies]
temp-env ={ version = "=0.3.6", features = ["async_closure"] }
env_logger = "*"
test-log = "0.2.11"
