version: "3.9"

services:
  api_keys:
    image: alpine
    environment:
    #add your api-keys here (put them after the "=" sign or use an .env file)
      # Set your YouTube API key
      - YT_API_KEY=${YT_API_KEY:-}
      # Set your Twitch secret
      - TWITCH_SECRET=${TWITCH_SECRET:-}
      # Set your Twitch client ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:-}

  vod2pod:
    extends: api_keys
    image: madiele/vod2pod-rss:beta
    build:
        context: .
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "80:8080"
    environment:
      - TZ=Europe/London #set if you want the logs to have you timezone
      - MP3_BITRATE=192 #bitrate in kilobits of the mp3 transcode
      - TRANSCODE=true #put to false if you only need feed generation
      - SUBFOLDER=/ #for reverse proxies, ex: "/" -> access the app at mywebsite.com ; vod2pod" -> access at mywebsite.com/vod2pod
      - RUST_LOG=DEBUG #set to DEBUG if you are having problems than open a github issue with the logs, use "sudo docker compose logs" to print them
      - TWITCH_TO_PODCAST_URL=ttprss #don't edit this
      - PODTUBE_URL=http://podtube:15000 #don't edit this
      - REDIS_ADDRESS=redis #don't edit this
      - REDIS_PORT=6379 #don't edit this

  ttprss: # you can remove this section and save some storage if you don't need twitch
    extends: api_keys
    build:
        context: https://github.com/madiele/TwitchToPodcastRSS.git
    image: madiele/twitch_to_podcast_rss
    restart: unless-stopped
    container_name: twitchToPodcastRSS
    environment:
        - TZ=Europe/London
        - TRANSCODE=False #keep this to false, the vod-to-podcast is what really matters

  podtube: #remove this section if you don't need improved youtube support
    extends: api_keys
    image: ftawesome/podtube
    environment:
      - YT_AUTOLOAD_NEWEST_AUDIO=False

  redis:
    image: "redis:6.2"
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
