version: '3.8'
services:
  api_keys:
    image: alpine
    environment:
    #add your api-keys here (put them after the "=" sign or use an .env file)
      # Set your YouTube API key
      - YT_API_KEY=${YT_API_KEY:-}
      # Set your Twitch secret
      - TWITCH_SECRET=${TWITCH_SECRET:-}
      # Set your Twitch client ID
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID:-}

  ttprss:
    extends: api_keys
    image: madiele/twitch_to_podcast_rss
    restart: unless-stopped
    container_name: twitchToPodcastRSS
    ports:
      - "8085:80"
    environment:
        - TZ=Europe/London
        - TRANSCODE=False

  podtube:
    extends: api_keys
    image: ftawesome/podtube
    ports:
      - "15000:15000"
    environment:
      - YT_AUTOLOAD_NEWEST_AUDIO=False

  redis:
    image: "redis:6.2"
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
