version: "3.9"

services:
  vod-to-podcast:
    build: .
    depends_on:
      - redis
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDRESS=redis
      - REDIS_PORT=6379
      - BITRATE=128
      - RUST_LOG=INFO
      - TWITCH_TO_PODCAST_URL=ttprss
      - TRANSCODE=true

  redis:
    image: "redis:6.2"
    command: redis-server --save 20 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5

  ttprss:
    build:
        context: https://github.com/madiele/TwitchToPodcastRSS.git
    image: madiele/twitch_to_podcast_rss
    restart: unless-stopped
    container_name: twitchToPodcastRSS
    environment:
        - TZ=Europe/London
        - TWITCH_SECRET=<YOUR_SECRET>
        - TWITCH_CLIENT_ID=<YOUR_CLIENT_ID>
        - TRANSCODE=False
